name: Main Build

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
      - name: Print Java Version
        run: java -version
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed --dry-run --verbose"
          version: v1.22.0
          skip-commit: true
  build:
    runs-on: ubuntu-latest
    needs: [formatting]
    strategy:
      matrix:
        java: [17]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package --file pom.xml
